2020-03-01 21:34:13,186 pypet ERROR    ERROR occurred during a single run! 
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/pypet/environment.py", line 259, in _sigint_handling_single_run
    return _single_run(kwargs)
  File "/usr/local/lib/python3.7/site-packages/pypet/environment.py", line 314, in _single_run
    result = runfunc(traj, *runargs, **kwrunparams)
  File "<ipython-input-30-cea1b9a39cea>", line 81, in exploreVal
    z = validateMod(4096, lgMult, lgAdd, traj.smMult, traj.smAdd, traj.mu, traj.sigma)
  File "<ipython-input-30-cea1b9a39cea>", line 76, in validateMod
    plt.show()
  File "/usr/local/lib/python3.7/site-packages/matplotlib/pyplot.py", line 269, in show
    return _show(*args, **kw)
  File "/usr/local/lib/python3.7/site-packages/ipykernel/pylab/backend_inline.py", line 43, in show
    metadata=_fetch_figure_metadata(figure_manager.canvas.figure)
  File "/usr/local/lib/python3.7/site-packages/IPython/core/display.py", line 313, in display
    format_dict, md_dict = format(obj, include=include, exclude=exclude)
  File "/usr/local/lib/python3.7/site-packages/IPython/core/formatters.py", line 180, in format
    data = formatter(obj)
  File "</usr/local/lib/python3.7/site-packages/decorator.py:decorator-gen-9>", line 2, in __call__
  File "/usr/local/lib/python3.7/site-packages/IPython/core/formatters.py", line 224, in catch_format_error
    r = method(self, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/IPython/core/formatters.py", line 341, in __call__
    return printer(obj)
  File "/usr/local/lib/python3.7/site-packages/IPython/core/pylabtools.py", line 248, in <lambda>
    png_formatter.for_type(Figure, lambda fig: print_figure(fig, 'png', **kwargs))
  File "/usr/local/lib/python3.7/site-packages/IPython/core/pylabtools.py", line 132, in print_figure
    fig.canvas.print_figure(bytes_io, **kw)
  File "/usr/local/lib/python3.7/site-packages/matplotlib/backend_bases.py", line 2069, in print_figure
    bbox_extra_artists=bbox_artists)
  File "/usr/local/lib/python3.7/site-packages/matplotlib/figure.py", line 2367, in get_tightbbox
    bbox = a.get_tightbbox(renderer)
  File "/usr/local/lib/python3.7/site-packages/matplotlib/axis.py", line 1162, in get_tightbbox
    ticks_to_draw = self._update_ticks()
  File "/usr/local/lib/python3.7/site-packages/matplotlib/axis.py", line 1087, in _update_ticks
    minor_locs = self.get_minorticklocs()
  File "/usr/local/lib/python3.7/site-packages/matplotlib/axis.py", line 1329, in get_minorticklocs
    major_locs = self.major.locator()
  File "/usr/local/lib/python3.7/site-packages/matplotlib/ticker.py", line 2081, in __call__
    return self.tick_values(vmin, vmax)
  File "/usr/local/lib/python3.7/site-packages/matplotlib/ticker.py", line 2089, in tick_values
    locs = self._raw_ticks(vmin, vmax)
  File "/usr/local/lib/python3.7/site-packages/matplotlib/ticker.py", line 2028, in _raw_ticks
    nbins = np.clip(self.axis.get_tick_space(),
  File "/usr/local/lib/python3.7/site-packages/matplotlib/axis.py", line 2491, in get_tick_space
    tick = self._get_tick(True)
  File "/usr/local/lib/python3.7/site-packages/matplotlib/axis.py", line 2223, in _get_tick
    return YTick(self.axes, 0, '', major=major, **tick_kw)
  File "/usr/local/lib/python3.7/site-packages/matplotlib/axis.py", line 161, in __init__
    self.label1 = self._get_text1()
  File "/usr/local/lib/python3.7/site-packages/matplotlib/axis.py", line 546, in _get_text1
    trans, vert, horiz = self._get_text1_transform()
  File "/usr/local/lib/python3.7/site-packages/matplotlib/axis.py", line 523, in _get_text1_transform
    return self.axes.get_yaxis_text1_transform(self._pad)
  File "/usr/local/lib/python3.7/site-packages/matplotlib/axes/_base.py", line 783, in get_yaxis_text1_transform
    self.figure.dpi_scale_trans),
  File "/usr/local/lib/python3.7/site-packages/matplotlib/transforms.py", line 1242, in __add__
    return composite_transform_factory(self, other)
KeyboardInterrupt
